Repository newrelic/newrelic-kubernetes-operator, pull requests merged in 2020-06, with the labels that each got.

#81 fix: set LeaderElectionID
  cmd/manager/main.go
Labels: bug

#84 chore(build): Force Github to fetch all history for linting, reset date
  .github/workflows/test.yml
  build/lint.mk
Labels: priority:blocker, size:S

#93 chore(deps): Update newrelic-client-go, test suite, k8s.io/*
  .github/renovate.json
  go.mod
  go.sum
Labels: dependencies, priority:medium, size:S

#94 chore(snyk): Change snyk action config
  .github/workflows/security.yml
Labels: priority:medium, size:S
